---
dist: xenial
language: python
python: 3.7
services: docker
env:
- OS_VERSION=bionic GIT_URL=https://github.com/ceph/ceph            GIT_REF=nautilus         IMG_TAG="popperized/ceph-builder:nautilus-bionic"
- OS_VERSION=bionic GIT_URL=https://github.com/ceph/ceph            GIT_REF=mimic            IMG_TAG="popperized/ceph-builder:mimic-bionic"
- OS_VERSION=bionic GIT_URL=https://github.com/ceph/ceph            GIT_REF=luminous         IMG_TAG="popperized/ceph-builder:luminous-bionic"
- OS_VERSION=bionic GIT_URL=https://github.com/uccross/skyhook-ceph GIT_REF=skyhook-luminous IMG_TAG="popperized/ceph-builder:skyhook-bionic"
install:
- git clone https://github.com/systemslab/popper /tmp/popper
- export PYTHONUNBUFFERED=1
- pip install /tmp/popper/cli
script: popper run
