---
dist: xenial
language: python
python: 3.7
services: docker
install:
- git clone --branch parser-bug-fix https://github.com/systemslab/popper /tmp/popper
- export PYTHONUNBUFFERED=1
- pip install /tmp/popper/cli
script: >-
  popper run -f ci/wf.yml
